Class {
	#name : #UIThemeColorConfigurator,
	#superclass : #Object,
	#category : #'UITheme-Color-Palette'
}

{ #category : #colors }
UIThemeColorConfigurator >> backgroundColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> badgeColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> badgeTextColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> balloonBackgroundColor [

	^ self subclassResponsibility
]

{ #category : #accessing }
UIThemeColorConfigurator >> baseColor [

	^ self subclassResponsibility
]

{ #category : #accessing }
UIThemeColorConfigurator >> basePassiveBackgroundColor [

	^ self subclassResponsibility
]

{ #category : #accessing }
UIThemeColorConfigurator >> baseSelectionColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> borderColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> buttonColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> caretColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> classExtensionColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> dangerTextColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> darkBaseColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> desktopColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> diffAdditionalLineBackgroundColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> diffEdgeColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> diffModificatedLineBackgroundColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> diffRemovedLinesBackgroundColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> disabledColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> dropListNormalFillStyleFor: anObject [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> dropListNormalListFillStyleFor: anObject [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> enabledColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> errorPopperBackgroundColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> lessConspicuousColorFrom: anObject [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> lightBackgroundColor [

	^ self subclassResponsibility
]

{ #category : #accessing }
UIThemeColorConfigurator >> lightBaseColor [

	^ self subclassResponsibility
]

{ #category : #accessing }
UIThemeColorConfigurator >> lightSelectionColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> lineNumberColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> listNormalFillStyleFor: anObject [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> listTextColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> menuBorderColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> menuItemDisabledTextColorFor: anObject [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> mouseOverColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> paginatorSelectionColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> popoverButtonColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> scrollbarColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> secondarySelectionColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> selectionColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> selectionTextColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> sliderNormalFillStyleFor: anObject [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> spotlightWindowColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> successTextColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> taskbarItemLabelColorForCollapsed: anObject [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> taskbarItemLabelColorForExpanded: anObject [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> testColorError [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> testColorFailure [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> testColorPassing [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> textColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> textColorForNonStandardBackground [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> textEditorNormalFillStyleFor: anObject [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> unfocusedSelectionColor [

	^ self subclassResponsibility
]

{ #category : #accessing }
UIThemeColorConfigurator >> veryLightSelectionColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> warningTextColor [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> windowActiveLabelFillStyleFor: anObject [

	^ self subclassResponsibility
]

{ #category : #colors }
UIThemeColorConfigurator >> windowColor [

	^ self subclassResponsibility
]
